import { useCallback, useState } from "react";
import { View, Text, StyleSheet, ScrollView, Pressable, ActivityIndicator } from "react-native";
import { useLocalSearchParams, useRouter, useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import Icon from "@react-native-vector-icons/ionicons";
import { spacing, radius, useTheme, makeStyles } from "@/src/theme";
import { Avatar } from "@/src/ui";
import { api } from "@/src/api";
import { MainTabBar } from "@/src/components/main-tab-bar";

export default function EventInvite() {
 const { colors } = useTheme();
 const styles = useStyles();
 const { id }=useLocalSearchParams<{id:string}>(); const router=useRouter();
 const [event,setEvent]=useState<any>(null); const [people,setPeople]=useState<any[]>([]); const [selected,setSelected]=useState<Set<string>>(new Set()); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [sent,setSent]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const [e,c]=await Promise.all([api.getEvent(id!),api.listConnections()]);setEvent(e.event);setPeople(c.connected||[])}finally{setLoading(false)}},[id]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const toggle=(uid:string)=>setSelected(s=>{const n=new Set(s);n.has(uid)?n.delete(uid):n.add(uid);return n});
 const send=async()=>{if(!id||selected.size===0)return;setSending(true);try{await api.inviteToEvent(id,[...selected]);setSent(true);setSelected(new Set())}finally{setSending(false)}};
 return <SafeAreaView style={styles.root} edges={["top"]}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Icon name="chevron-back" size={24} color={colors.onSurface}/></Pressable><View style={{flex:1}}><Text style={styles.title}>Invite friends</Text><Text numberOfLines={1} style={styles.event}>{event?.title||"Event"}</Text></View></View>
 <ScrollView contentContainerStyle={styles.content}>{sent?<View style={styles.success}><Icon name="checkmark-circle" size={24} color={colors.brandPrimary}/><View><Text style={styles.successTitle}>Invitations sent</Text><Text style={styles.successText}>They'll see this event in Activity.</Text></View></View>:null}
 <Text style={styles.heading}>Your connections</Text><Text style={styles.sub}>Choose people you'd like to go with.</Text>
 {loading?<ActivityIndicator color={colors.brandPrimary}/>:people.length===0?<View style={styles.empty}><Icon name="people-outline" size={34} color={colors.muted}/><Text style={styles.emptyTitle}>No connections yet</Text><Text style={styles.emptyText}>Connect with people in Discover first, then you can invite them to events.</Text></View>:people.map((x:any)=>{const u=x.user,on=selected.has(u.id);return <Pressable key={u.id} onPress={()=>toggle(u.id)} style={[styles.person,on&&styles.personOn]}><Avatar uri={u.profile_photo_url} name={u.first_name} size={46}/><View style={{flex:1}}><Text style={styles.name}>{u.first_name} {u.last_name}</Text><Text style={styles.meta}>{u.major||u.university||"Connection"}</Text></View><View style={[styles.check,on&&styles.checkOn]}>{on?<Icon name="checkmark" size={16} color={colors.onBrandPrimary}/>:null}</View></Pressable>})}
 </ScrollView><View style={styles.footer}><Pressable disabled={selected.size===0||sending} onPress={send} style={[styles.send,(selected.size===0||sending)&&{opacity:.45}]}><Text style={styles.sendText}>{sending?"Sending...":`Send invite${selected.size===1?"":selected.size>1?"s":""}${selected.size?` (${selected.size})`:""}`}</Text></Pressable></View><MainTabBar/></SafeAreaView>
}
const useStyles = makeStyles((colors) => ({root:{flex:1,backgroundColor:colors.surface},header:{flexDirection:"row",alignItems:"center",gap:spacing.sm,paddingHorizontal:spacing.lg,paddingVertical:spacing.md,borderBottomWidth:1,borderBottomColor:colors.divider},back:{width:42,height:42,alignItems:"center",justifyContent:"center"},title:{fontSize:18,fontWeight:"800",color:colors.onSurface},event:{fontSize:11,color:colors.muted,marginTop:1},content:{padding:spacing.xl,paddingBottom:180},heading:{fontSize:23,fontWeight:"800",color:colors.onSurface},sub:{fontSize:13,color:colors.muted,marginTop:4,marginBottom:spacing.lg},person:{flexDirection:"row",alignItems:"center",gap:spacing.md,padding:spacing.md,borderRadius:radius.lg,backgroundColor:colors.surfaceSecondary,borderWidth:1,borderColor:colors.border,marginBottom:spacing.sm},personOn:{borderColor:colors.brandPrimary,backgroundColor:colors.brandTertiary},name:{fontSize:14,fontWeight:"800",color:colors.onSurface},meta:{fontSize:11,color:colors.muted,marginTop:2},check:{width:28,height:28,borderRadius:14,borderWidth:2,borderColor:colors.border,alignItems:"center",justifyContent:"center"},checkOn:{backgroundColor:colors.brandPrimary,borderColor:colors.brandPrimary},footer:{position:"absolute",left:0,right:0,bottom:57,padding:spacing.lg,backgroundColor:colors.surface,borderTopWidth:1,borderTopColor:colors.divider},send:{alignItems:"center",paddingVertical:14,borderRadius:radius.pill,backgroundColor:colors.brandPrimary},sendText:{fontSize:14,fontWeight:"800",color:colors.onBrandPrimary},success:{flexDirection:"row",gap:spacing.sm,padding:spacing.md,borderRadius:radius.lg,backgroundColor:colors.brandTertiary,marginBottom:spacing.xl},successTitle:{fontSize:13,fontWeight:"800",color:colors.onBrandTertiary},successText:{fontSize:11,color:colors.onBrandTertiary,marginTop:2},empty:{alignItems:"center",paddingVertical:48},emptyTitle:{fontSize:15,fontWeight:"800",color:colors.onSurface,marginTop:spacing.md},emptyText:{fontSize:12,lineHeight:18,color:colors.muted,textAlign:"center",marginTop:4,maxWidth:300}}));
