import { useCallback, useState } from "react";
import { View, Text, StyleSheet, ScrollView, Pressable, ActivityIndicator } from "react-native";
import { useRouter, useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import Icon from "@react-native-vector-icons/ionicons";
import { spacing, radius, useTheme, makeStyles } from "@/src/theme";
import { Avatar } from "@/src/ui";
import { MainTabBar } from "@/src/components/main-tab-bar";
import { api } from "@/src/api";

export default function Activity() {
 const { colors } = useTheme();
 const styles = useStyles();
 const router=useRouter(); const [data,setData]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const [n,c]=await Promise.all([api.notifications(),api.listConnections()]);const incoming=(c.incoming||[]).map((x:any)=>({id:`connection-${x.id}`,type:"connection",title:`${x.user.first_name} wants to connect`,body:x.reasons?.[0]||"You might vibe.",actor:x.user,connection_id:x.id,created_at:x.created_at,read:false}));setData([...incoming,...(n.notifications||[])]);}catch{}setLoading(false)},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const open=(x:any)=>{if(x.type==="connection"&&x.actor?.id)router.push(`/match/${x.actor.id}`);else if(x.entity_type==="event"&&x.entity_id)router.push(`/event/${x.entity_id}`);else if(x.entity_type==="circle"&&x.entity_id)router.push(`/circle/${x.entity_id}`);else if(x.type==="daily_circle")router.push("/daily-circle");};
 const accept=async(x:any)=>{await api.acceptConnection(x.connection_id);load()}; const decline=async(x:any)=>{await api.declineConnection(x.connection_id);load()};
 return <SafeAreaView style={styles.root} edges={["top"]}><View style={styles.header}><Pressable onPress={()=>router.replace("/(tabs)/home")} style={styles.back}><Icon name="chevron-back" size={24} color={colors.onSurface}/></Pressable><Text style={styles.title}>Activity</Text><Pressable onPress={async()=>{await api.readAllNotifications();load()}}><Text style={styles.read}>Read all</Text></Pressable></View>
 <ScrollView contentContainerStyle={styles.content}><Text style={styles.heading}>What's happening</Text><Text style={styles.sub}>Invites, connections and things worth doing.</Text>
 {loading?<ActivityIndicator color={colors.brandPrimary}/>:data.length===0?<View style={styles.empty}><Icon name="notifications-outline" size={34} color={colors.muted}/><Text style={styles.emptyTitle}>You're all caught up</Text><Text style={styles.emptyText}>New connections, Circle matches and invitations will show up here.</Text></View>:data.map((x:any)=><Pressable key={x.id} onPress={()=>open(x)} style={styles.item}><View style={styles.avatar}>{x.actor?<Avatar uri={x.actor.profile_photo_url} name={x.actor.first_name} size={44}/>:<Icon name={x.type==="event_invite"?"calendar":"sparkles"} size={20} color={colors.brandPrimary}/>}</View><View style={{flex:1}}><Text style={styles.itemTitle}>{x.title}</Text><Text style={styles.itemText}>{x.body}</Text>{x.type==="connection"?<View style={styles.actions}><Pressable onPress={()=>accept(x)} style={styles.primary}><Text style={styles.primaryText}>Accept</Text></Pressable><Pressable onPress={()=>decline(x)} style={styles.secondary}><Text style={styles.secondaryText}>Decline</Text></Pressable></View>:null}</View>{!x.read&&x.type!=="connection"?<View style={styles.dot}/>:null}</Pressable>)}
 </ScrollView><MainTabBar/></SafeAreaView>
}
const useStyles = makeStyles((colors) => ({root:{flex:1,backgroundColor:colors.surface},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:spacing.lg,paddingVertical:spacing.md,borderBottomWidth:1,borderBottomColor:colors.divider},back:{width:42,height:42,alignItems:"center",justifyContent:"center"},title:{fontSize:17,fontWeight:"700",color:colors.onSurface},read:{fontSize:12,fontWeight:"700",color:colors.brandPrimary},content:{padding:spacing.xl,paddingBottom:120},heading:{fontSize:27,fontWeight:"800",color:colors.onSurface},sub:{fontSize:14,color:colors.muted,marginTop:4,marginBottom:spacing.xl},item:{flexDirection:"row",alignItems:"flex-start",gap:spacing.md,paddingVertical:spacing.lg,borderBottomWidth:1,borderBottomColor:colors.divider},avatar:{width:44,height:44,borderRadius:22,backgroundColor:colors.brandTertiary,alignItems:"center",justifyContent:"center",overflow:"hidden"},itemTitle:{fontSize:14,fontWeight:"800",color:colors.onSurface},itemText:{fontSize:12,lineHeight:17,color:colors.muted,marginTop:2},dot:{width:8,height:8,borderRadius:4,backgroundColor:colors.brandPrimary,marginTop:6},actions:{flexDirection:"row",gap:spacing.sm,marginTop:spacing.sm},primary:{paddingHorizontal:14,paddingVertical:8,borderRadius:radius.pill,backgroundColor:colors.brandPrimary},primaryText:{fontSize:11,fontWeight:"800",color:colors.onBrandPrimary},secondary:{paddingHorizontal:14,paddingVertical:8,borderRadius:radius.pill,backgroundColor:colors.surfaceSecondary},secondaryText:{fontSize:11,fontWeight:"700",color:colors.onSurface},empty:{alignItems:"center",paddingVertical:48},emptyTitle:{fontSize:15,fontWeight:"800",color:colors.onSurface,marginTop:spacing.md},emptyText:{fontSize:12,lineHeight:18,color:colors.muted,textAlign:"center",marginTop:4,maxWidth:300}}));
