import { useState } from "react";
import { View, Text, StyleSheet, Pressable, TextInput, ScrollView, Alert } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import Icon from "@react-native-vector-icons/ionicons";
import { api } from "@/src/api";
import { colors, spacing, radius } from "@/src/theme";

const intents = [
  ["post", "Just share", "chatbubble-outline"], ["anyone_down", "Anyone down?", "people-outline"],
  ["looking_for_people", "Looking for people", "search-outline"], ["question", "Question", "help-circle-outline"],
  ["recommendation", "Recommendation", "bulb-outline"],
] as const;

export default function CreatePost() {
 const router=useRouter(); const [content,setContent]=useState(""); const [intent,setIntent]=useState("post");
 const [audience,setAudience]=useState<"campus"|"connections">("campus"); const [busy,setBusy]=useState(false);
 const [place,setPlace]=useState(""); const [when,setWhen]=useState(""); const [capacity,setCapacity]=useState("");
 const actionable=["anyone_down","looking_for_people"].includes(intent);
 const submit=async()=>{const text=content.trim();if(!text||busy)return;let plan_time:string|undefined;
   if(actionable&&when.trim()){const parsed=new Date(when.trim());if(Number.isNaN(parsed.getTime())){Alert.alert("Check the time","Try something like: Sep 25 7:30 PM");return;}plan_time=parsed.toISOString();}
   const cap=capacity.trim()?Number(capacity):undefined;if(cap!==undefined&&(!Number.isInteger(cap)||cap<2||cap>100)){Alert.alert("Check group size","Choose a number from 2 to 100.");return;}
   setBusy(true);try{await api.createPost({content:text,intent,audience,place_name:actionable&&place.trim()?place.trim():undefined,plan_time,capacity:actionable?cap:undefined});router.back()}catch(e:any){Alert.alert("Couldn't post",e?.message||"Try again.")}finally{setBusy(false)}
 };
 return <SafeAreaView style={s.page}><View style={s.header}><Pressable onPress={()=>router.back()}><Icon name="close" size={26} color={colors.onSurface}/></Pressable><Text style={s.title}>Create post</Text><Pressable onPress={submit} disabled={!content.trim()||busy} style={[s.postBtn,(!content.trim()||busy)&&{opacity:.45}]}><Text style={s.postBtnText}>{busy?"Posting...":"Post"}</Text></Pressable></View>
 <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><TextInput value={content} onChangeText={setContent} multiline autoFocus maxLength={1000} placeholder="What's happening? Find people, make a plan, ask something..." placeholderTextColor={colors.muted} style={s.input}/><Text style={s.count}>{content.length}/1000</Text>
 <Text style={s.label}>What's the vibe?</Text><View style={s.wrap}>{intents.map(([key,label,icon])=><Pressable key={key} onPress={()=>setIntent(key)} style={[s.intent,intent===key&&s.intentOn]}><Icon name={icon as any} size={16} color={intent===key?colors.onBrandPrimary:colors.brandPrimary}/><Text style={[s.intentText,intent===key&&s.intentTextOn]}>{label}</Text></Pressable>)}</View>
 {actionable&&<View style={s.plan}><View style={s.planHead}><Icon name="flash-outline" size={19} color={colors.brandPrimary}/><View><Text style={s.planTitle}>Turn this into a plan</Text><Text style={s.planSub}>Optional details make it easier for people to join.</Text></View></View>
 <Text style={s.fieldLabel}>Where?</Text><TextInput value={place} onChangeText={setPlace} maxLength={160} placeholder="TSU, library, downtown Fullerton..." placeholderTextColor={colors.muted} style={s.field}/>
 <Text style={s.fieldLabel}>When?</Text><TextInput value={when} onChangeText={setWhen} placeholder="Sep 25 7:30 PM" placeholderTextColor={colors.muted} style={s.field}/><Text style={s.hint}>Leave blank if you're still figuring it out.</Text>
 <Text style={s.fieldLabel}>Group size</Text><TextInput value={capacity} onChangeText={setCapacity} keyboardType="number-pad" placeholder="Optional, e.g. 6" placeholderTextColor={colors.muted} style={s.field}/></View>}
 <Text style={s.label}>Who can see it?</Text><View style={s.audienceRow}><Pressable onPress={()=>setAudience("campus")} style={[s.audience,audience==="campus"&&s.audienceOn]}><Icon name="school-outline" size={18} color={audience==="campus"?colors.onBrandPrimary:colors.brandPrimary}/><Text style={[s.intentText,audience==="campus"&&s.intentTextOn]}>Campus</Text></Pressable><Pressable onPress={()=>setAudience("connections")} style={[s.audience,audience==="connections"&&s.audienceOn]}><Icon name="people-outline" size={18} color={audience==="connections"?colors.onBrandPrimary:colors.brandPrimary}/><Text style={[s.intentText,audience==="connections"&&s.intentTextOn]}>Connections</Text></Pressable></View>
 <View style={s.note}><Icon name="sparkles" size={18} color={colors.brandPrimary}/><Text style={s.noteText}>{actionable?"People can tap I'm down and join the plan. Once there's a crew, Circle can turn it into a group chat.":"Posts on Circle are meant to start conversations and real plans — not chase likes."}</Text></View></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.surface},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",padding:spacing.lg,borderBottomWidth:1,borderBottomColor:colors.divider},title:{fontSize:17,fontWeight:"900",color:colors.onSurface},postBtn:{backgroundColor:colors.brandPrimary,borderRadius:radius.pill,paddingHorizontal:16,paddingVertical:9},postBtnText:{color:colors.onBrandPrimary,fontWeight:"800"},content:{padding:spacing.xl,paddingBottom:50},input:{minHeight:150,color:colors.onSurface,fontSize:19,lineHeight:27,textAlignVertical:"top"},count:{textAlign:"right",fontSize:11,color:colors.muted},label:{fontSize:13,fontWeight:"800",color:colors.onSurface,marginTop:spacing.xl,marginBottom:spacing.sm},wrap:{flexDirection:"row",flexWrap:"wrap",gap:8},intent:{flexDirection:"row",alignItems:"center",gap:6,paddingHorizontal:12,paddingVertical:9,borderRadius:radius.pill,borderWidth:1,borderColor:colors.border},intentOn:{backgroundColor:colors.brandPrimary,borderColor:colors.brandPrimary},intentText:{fontSize:12,fontWeight:"700",color:colors.onSurface},intentTextOn:{color:colors.onBrandPrimary},plan:{marginTop:spacing.lg,padding:spacing.lg,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.surfaceSecondary},planHead:{flexDirection:"row",alignItems:"center",gap:9},planTitle:{fontSize:14,fontWeight:"900",color:colors.onSurface},planSub:{fontSize:11,color:colors.muted,marginTop:2},fieldLabel:{fontSize:11,fontWeight:"800",color:colors.onSurface,marginTop:14,marginBottom:6},field:{borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:12,paddingVertical:10,color:colors.onSurface,backgroundColor:colors.surface},hint:{fontSize:10,color:colors.muted,marginTop:5},audienceRow:{flexDirection:"row",gap:10},audience:{flex:1,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7,padding:12,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg},audienceOn:{backgroundColor:colors.brandPrimary,borderColor:colors.brandPrimary},note:{flexDirection:"row",gap:9,marginTop:spacing.xl,padding:spacing.md,backgroundColor:colors.brandTertiary,borderRadius:radius.lg},noteText:{flex:1,color:colors.onSurface,fontSize:12,lineHeight:17}});
