import { useCallback, useState } from "react";
import { View, Text, StyleSheet, Pressable, FlatList, TextInput, KeyboardAvoidingView, Platform } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useLocalSearchParams, useRouter, useFocusEffect } from "expo-router";
import Icon from "@react-native-vector-icons/ionicons";
import { api } from "@/src/api";
import { Avatar } from "@/src/ui";
import { colors, spacing, radius } from "@/src/theme";
import { useAuth } from "@/src/auth";

export default function PostDetail(){
 const {id}=useLocalSearchParams<{id:string}>(); const router=useRouter(); const {user}=useAuth();
 const [post,setPost]=useState<any>(null); const [replies,setReplies]=useState<any[]>([]); const [text,setText]=useState(""); const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const [p,r]=await Promise.all([api.listPosts(),api.listPostReplies(id!)]);setPost((p.posts||[]).find((x:any)=>x.id===id));setReplies(r.replies||[])}catch{}},[id]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const send=async()=>{if(!text.trim()||busy)return;setBusy(true);try{const r=await api.createPostReply(id!,text.trim());setReplies(x=>[...x,r.reply]);setText("")}finally{setBusy(false)}};
 const join=async()=>{const r=await api.togglePostInterest(id!);setPost((p:any)=>({...p,interest_count:Math.max(0,(p.interest_count||0)+(r.interested?1:-1)),interest_user_ids:r.interested?[...(p.interest_user_ids||[]),user?.id]:(p.interest_user_ids||[]).filter((x:string)=>x!==user?.id)}))};
 if(!post)return <SafeAreaView style={s.page}><Text style={s.loading}>Loading...</Text></SafeAreaView>;
 const actionable=["anyone_down","looking_for_people"].includes(post.intent); const joined=(post.interest_user_ids||[]).includes(user?.id);
 return <KeyboardAvoidingView style={s.page} behavior={Platform.OS==="ios"?"padding":undefined}><SafeAreaView edges={["top"]}><View style={s.header}><Pressable onPress={()=>router.back()}><Icon name="chevron-back" size={26} color={colors.onSurface}/></Pressable><Text style={s.title}>Post</Text><View style={{width:26}}/></View></SafeAreaView>
 <FlatList data={replies} keyExtractor={(x:any)=>x.id} contentContainerStyle={s.list} ListHeaderComponent={<View style={s.post}><View style={s.author}><Avatar uri={post.author?.profile_photo_url} name={post.author?.first_name} size={46}/><View><Text style={s.name}>{post.author?.first_name} {post.author?.last_name}</Text><Text style={s.meta}>{post.intent==="anyone_down"?"Anyone down?":post.intent==="looking_for_people"?"Looking for people":post.intent==="question"?"Question":post.intent==="recommendation"?"Recommendation":"Post"} · {post.audience==="connections"?"Connections":"Campus"}</Text></View></View><Text style={s.body}>{post.content}</Text>{post.place_name&&<Text style={s.detail}>📍 {post.place_name}</Text>}{actionable&&<Pressable onPress={join} style={[s.down,joined&&s.downOn]}><Icon name={joined?"checkmark":"people-outline"} size={18} color={joined?colors.onBrandPrimary:colors.brandPrimary}/><Text style={[s.downText,joined&&{color:colors.onBrandPrimary}]}>{joined?"I'm down": "I'm down"} · {post.interest_count||0}</Text></Pressable>}<Text style={s.repliesTitle}>Conversation</Text></View>} renderItem={({item}:any)=><View style={s.reply}><Avatar uri={item.author?.profile_photo_url} name={item.author?.first_name} size={34}/><View style={s.replyBody}><Text style={s.replyName}>{item.author?.first_name}</Text><Text style={s.replyText}>{item.content}</Text></View></View>} ListEmptyComponent={<Text style={s.empty}>No replies yet. Start the conversation.</Text>}/>
 <SafeAreaView edges={["bottom"]} style={s.composer}><TextInput value={text} onChangeText={setText} placeholder="Reply..." placeholderTextColor={colors.muted} style={s.input}/><Pressable onPress={send} style={s.send}><Icon name="arrow-up" size={18} color={colors.onBrandPrimary}/></Pressable></SafeAreaView>
 </KeyboardAvoidingView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.surface},loading:{padding:24,color:colors.muted},header:{height:54,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:spacing.lg,borderBottomWidth:1,borderBottomColor:colors.divider},title:{fontSize:17,fontWeight:"900",color:colors.onSurface},list:{padding:spacing.xl,paddingBottom:40},post:{paddingBottom:spacing.lg},author:{flexDirection:"row",alignItems:"center",gap:10},name:{fontSize:15,fontWeight:"800",color:colors.onSurface},meta:{fontSize:11,color:colors.muted,marginTop:2},body:{fontSize:18,lineHeight:26,color:colors.onSurface,marginTop:spacing.lg},detail:{fontSize:13,color:colors.muted,marginTop:10},down:{marginTop:spacing.lg,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7,borderWidth:1,borderColor:colors.brandPrimary,borderRadius:radius.pill,padding:11},downOn:{backgroundColor:colors.brandPrimary},downText:{color:colors.brandPrimary,fontWeight:"800"},repliesTitle:{fontSize:14,fontWeight:"900",color:colors.onSurface,marginTop:spacing.xl,paddingTop:spacing.lg,borderTopWidth:1,borderTopColor:colors.divider},reply:{flexDirection:"row",gap:9,paddingVertical:11},replyBody:{flex:1,backgroundColor:colors.surfaceSecondary,borderRadius:radius.lg,padding:10},replyName:{fontSize:12,fontWeight:"800",color:colors.onSurface},replyText:{fontSize:14,lineHeight:19,color:colors.onSurface,marginTop:2},empty:{color:colors.muted,textAlign:"center",padding:30},composer:{flexDirection:"row",gap:8,padding:spacing.md,borderTopWidth:1,borderTopColor:colors.divider,backgroundColor:colors.surface},input:{flex:1,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surfaceSecondary,borderRadius:radius.pill,paddingHorizontal:16,color:colors.onSurface},send:{width:40,height:40,borderRadius:20,backgroundColor:colors.brandPrimary,alignItems:"center",justifyContent:"center"}});
